# Generated by Django 4.0.4 on 2022-05-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
