# Generated by Django 4.0.4 on 2022-05-16 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysisapp', '0002_analysis_text_analysis_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='irony',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='analysis',
            name='score_tag',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
